### PR TITLE
Added ICS file support

### PR DESCRIPTION
**Pull request by lorddusk**
This adds support for ICS files, implements #9 

Creates an ics file on download click, that functions the same as the google calendar link:
image

I was not sure if you used a formatter, so I left everything default.

### CODE REVIEW

**Comment by AyronK** [comment]
Thank you for the PR, I will get back to it later this week. I would like to consider alternatives first. At the moment I am busy gathering feedback, creating issues and setting up a workplace for contributors.

**Review by AyronK — APPROVED** [review]
:shipit: ✅, just merge main and resolve a conflict please, the mobile layout of the card has changed a bit, please confirm that your button fits well afterwards.

**Comment by lorddusk** [comment]
Mobile:
image

Desktop:
image

**Comment by AyronK** [comment]
Looks good, I tested it with outlook. Thank's for your work :)

**Pull request merged**
